version: '3'
services:
  app:
    build: .
    environment:
      - FLASK_ENV=development
    ports:
      - 8080:80
    networks:
      - private

  redis:
    image: redis:4.0.11-alpine
    networks:
      - private
    volumes:
      - ~/flask-redis/data:/data

networks:
  private:

